import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final appLocaleProvider = StateProvider<Locale>((ref) => const Locale('en'));

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('te')];

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  static AppStrings of(BuildContext context) {
    final strings = Localizations.of<AppStrings>(context, AppStrings);
    assert(strings != null, 'AppStrings not found in context.');
    return strings!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'CropPulse',
      'nav_home': 'Home',
      'nav_intelligence': 'Intelligence',
      'nav_farmer': 'Farmer',
      'nav_trader': 'Trader',
      'nav_customer': 'Customer',
      'nav_market': 'Market',
      'nav_profile': 'Profile',
      'select_role': 'Select role',
      'select_language': 'Select language',
      'role_farmer': 'Farmer',
      'role_trader': 'Trader',
      'role_exporter': 'Exporter',
      'role_customer': 'Customer',
      'lang_english': 'English',
      'lang_hindi': 'Hindi',
      'lang_telugu': 'Telugu',
      'daily_feed_title': 'Daily Intelligence Feed',
      'daily_feed_subtitle': 'Real-time market alerts and AI recommendations',
      'need_recommendation': 'Need a selling recommendation?',
      'need_recommendation_desc':
          'Open the price advisor to fetch live market guidance from the Phase 2 API or use offline fallback data.',
      'open_price_advisor': 'Open Price Advisor',
      'alert_rice_title': 'Rice prices rising (8.5%)',
      'alert_rice_subtitle': 'Peak demand expected in next 48 hours',
      'alert_rice_action': 'Best selling window opening',
      'alert_peak_title': 'Peak demand conditions',
      'alert_peak_subtitle': 'Demand at 92% with maximum buyer interest',
      'alert_peak_action': 'Optimal selling window',
      'alert_rain_title': 'Heavy rainfall expected',
      'alert_rain_subtitle': 'May reduce supply in the next 2 to 3 weeks',
      'alert_rain_action': 'Monitor supply closely',
      'alert_sell_title': 'Best time to sell: Next 48 hours',
      'alert_sell_subtitle': 'Price forecast: ₹2,650/kg during peak demand',
      'alert_sell_action': 'Recommend selling now',
      'farmer_hub_title': 'Farmer Hub',
      'farmer_operating_system': 'Farmer Operating System',
      'crop_planning': 'Crop Planning',
      'crop_planning_desc': 'Plan crops with profitability analysis',
      'best_time_sell': 'Best Time to Sell',
      'best_time_sell_desc': 'AI predicts the optimal harvest date',
      'weather_alerts': 'Weather Alerts',
      'weather_alerts_desc': 'Real-time weather and disease alerts',
      'buyer_discovery': 'Buyer Discovery',
      'buyer_discovery_desc': 'Connect with verified buyers',
      'open': 'Open',
      'available_now': 'Available now',
      'coming_soon': 'Coming soon',
      'trader_hub_title': 'Trader Hub',
      'procurement_intelligence': 'Procurement Intelligence',
      'supply_visibility': 'Supply Visibility',
      'supply_visibility_desc': 'Real-time inventory across mandis',
      'demand_forecasting': 'Demand Forecasting',
      'demand_forecasting_desc': 'Predict buyer demand by region',
      'regional_arbitrage': 'Regional Arbitrage',
      'regional_arbitrage_desc': 'Identify price gaps for profit',
      'inventory_tracking': 'Inventory Tracking',
      'inventory_tracking_desc': 'Track purchased inventory',
      'customer_hub_title': 'Customer Hub',
      'customer_buying_desk': 'Customer Buying Desk',
      'customer_buying_desc':
          'Customers can browse vegetables, pulses, oilseeds, spices, and other crops, compare offers, and buy from farmers and traders in one place.',
      'customer_marketplace_cta': 'Browse marketplace crops',
      'customer_intelligence_cta': 'Review market intelligence',
      'customer_price_cta': 'Check price guidance',
      'customer_card_market_title': 'All crops in one place',
      'customer_card_market_desc':
          'Browse crop availability across farmers and traders for vegetables, pulses, oilseeds, spices, and staple crops.',
      'customer_card_buyers_title': 'Buy with confidence',
      'customer_card_buyers_desc':
          'See location, quality, and pricing before you place an offer.',
      'customer_card_guidance_title': 'Know market timing',
      'customer_card_guidance_desc':
          'Use intelligence and price advisor tools before purchasing.',
      'marketplace_title': 'Marketplace',
      'buy_orders': 'Buy Orders',
      'sell_orders': 'Sell Orders',
      'customer_buy_banner':
          'Customers can review live crop listings and buy from farmers and traders by sending buying offers from this marketplace.',
      'crop': 'Crop',
      'state': 'State',
      'state_filter': 'State filter',
      'sync_listings': 'Sync Listings',
      'no_live_sell_listings':
          'No live sell listings yet. Use the add button to publish one to the marketplace backend.',
      'create_listing': 'Create Listing',
      'crop_id': 'Crop ID',
      'quantity_kg': 'Quantity (kg)',
      'quality_grade': 'Quality Grade',
      'price_per_kg': 'Price per kg',
      'available_date': 'Available Date (YYYY-MM-DD)',
      'description': 'Description',
      'enter_valid_quantity_price':
          'Enter valid numeric values for quantity and price.',
      'publish_listing': 'Publish Listing',
      'ready_to_purchase': 'Ready to purchase quickly.',
      'make_offer_for': 'Make Offer for {crop}',
      'seller': 'Seller: {name}',
      'offer_price_per_kg': 'Offer price per kg',
      'pickup_location': 'Pickup location',
      'message': 'Message',
      'submit_offer': 'Submit Offer',
      'enter_valid_offer_quantity':
          'Enter valid numeric values for offer and quantity.',
      'available': 'Available: {value}',
      'make_offer': 'Send buying offer',
      'available_on_views': 'Available on {date} · {views} views',
      'intelligence_title': 'Market Intelligence',
      'select_commodity': 'Select Commodity',
      'price_chart_30_days': 'Price Chart (30 Days)',
      'ai_price_advisor': 'AI Price Advisor',
      'ai_price_advisor_desc':
          'Request a crop-specific recommendation from the Phase 2 intelligence API, including nearby mandi prices and the best selling time.',
      'supply_vs_demand': 'Supply vs Demand',
      'supply_level': 'Supply Level',
      'inventory_status': 'Inventory status',
      'demand_level': 'Demand Level',
      'buyer_interest': 'Buyer interest',
      'price_advisor_title': 'Price Advisor',
      'live_selling_guidance': 'Live selling guidance',
      'live_selling_guidance_desc':
          'Query the CropPulse Phase 2 intelligence API for recommended price, nearby mandi comparisons, and best selling window.',
      'request_inputs': 'Request inputs',
      'fetch_recommendation': 'Fetch recommendation',
      'enter_valid_quantity': 'Enter a valid quantity in kilograms.',
      'offline_fallback':
          'Showing offline fallback data because the mobile app could not reach the API.',
      'recommendation_suffix': '{crop} Recommendation',
      'recommended_price': 'Recommended price',
      'market_trend': 'Market trend',
      'best_selling_time': 'Best selling time: {value}',
      'nearby_markets': 'Nearby markets',
      'profile_title': 'Profile',
      'guest_user': 'Guest user',
      'acres': 'Acres',
      'profile': 'Profile',
      'synced_farmer_profile': 'Synced Farmer Profile',
      'soil': 'Soil: {value}',
      'edit_farmer_profile': 'Edit Farmer Profile',
      'login': 'Sign In',
      'logout': 'Log Out',
      'transaction_history': 'Transaction History',
      'saved_listings': 'Saved Listings',
      'settings': 'Settings',
      'help_support': 'Help and Support',
      'account_sync_later': 'Account Sync Coming Later',
      'account_sync_message':
          'Account sync will be added after the core mobile experience is finalized.',
      'sign_in_title': 'Sign in to CropPulse',
      'sign_in_desc':
          'Use your mobile number to receive a secure one-time verification code.',
      'phone_number': 'Phone number',
      'request_otp': 'Request OTP',
      'verify_otp': 'Verify OTP',
      'resend_otp': 'Resend OTP',
      'otp': 'OTP',
      'farmer_profile_title': 'Farmer Profile',
      'sync_profile': 'Sync Profile',
      'save_profile': 'Save Profile',
      'saving': 'Saving...',
      'fill_required_fields': 'Fill every required field with valid values.',
      'backend_profile_snapshot': 'Backend Profile Snapshot',
      'name': 'Name',
      'phone': 'Phone',
      'kyc': 'KYC',
      'land_size': 'Land Size: {value} acres',
      'created': 'Created: {value}',
      'farmer_profile_form': 'Farmer Profile Form',
      'district': 'District',
      'village': 'Village',
      'land_size_acres': 'Land Size (acres)',
      'soil_type': 'Soil Type',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'bank_account_optional': 'Bank Account (optional)',
      'preview_local_draft':
          'Preview mode: using a local farmer profile draft on this device.',
      'farmer_profile_synced_success': 'Farmer profile synced successfully.',
      'could_not_load_farmer_profile': 'Could not load farmer profile.',
      'preview_saved_locally':
          'Preview mode: profile saved locally on this device.',
      'farmer_profile_saved_success': 'Farmer profile saved successfully.',
      'could_not_save_farmer_profile': 'Could not save farmer profile.',
      'signed_in_successfully': 'Signed in successfully.',
      'could_not_request_otp': 'Could not request OTP.',
      'could_not_verify_otp': 'Could not verify OTP.',
      'mock_code_suffix': 'Use the mock code 123456 for now.',
      'nav_categories': 'Categories',
      'nav_search': 'Search',
      'nav_cart': 'Cart',
      'nav_account': 'Account',
      'categories': 'Categories',
      'all': 'All',
      'view_all': 'View all',
      'available_products': 'Available products',
      'no_products': 'No products are currently available.',
      'search': 'Search',
      'search_products': 'Search vegetables, fruits, grains...',
      'search_prompt': 'Enter a product or category to search.',
      'add_to_cart': 'Add to cart',
      'in_cart': '{quantity} in cart',
      'not_available': 'Not available',
      'price_unavailable': 'Price unavailable',
      'minimum_quantity': 'Minimum quantity',
      'grade': 'Grade',
      'description_unavailable': 'Product information is unavailable.',
      'cart': 'Cart',
      'empty_cart': 'Your cart is empty.',
      'browse_categories': 'Browse categories',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery fee',
      'total': 'Total',
      'cart_location_required': 'Select a delivery location to validate stock.',
      'resolve_cart_issues': 'Resolve cart issues',
      'checkout_next_step': 'Checkout is the next implementation step',
      'set_delivery_area': 'Set delivery area',
      'delivery_to': 'Delivery to',
      'pincode': 'Pincode',
      'check_delivery': 'Check delivery',
      'check_serviceability': 'Check delivery availability',
      'invalid_pincode': 'Enter a valid 6-digit Indian pincode.',
      'serviceable': 'Delivery available',
      'temporarily_unavailable': 'Temporarily unavailable',
      'not_serviceable': 'Delivery unavailable',
      'commerce_offline':
          'You appear to be offline. Check your connection and try again.',
      'commerce_error': 'CropPulse could not load this information.',
      'retry': 'Retry',
      'addresses': 'Addresses',
      'add_address': 'Add address',
      'edit_address': 'Edit address',
      'manage_addresses': 'Manage saved delivery addresses',
      'default_address': 'Default',
      'make_default': 'Make default',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'sign_in_for_addresses':
          'Sign in to save addresses and restore your cart.',
      'address_label': 'Label',
      'address_recipient_name': 'Recipient name',
      'address_recipient_phone': 'Recipient phone',
      'address_line1': 'Address line 1',
      'address_line2': 'Address line 2',
      'address_landmark': 'Landmark',
      'address_locality': 'Locality',
      'address_district': 'District',
      'address_state': 'State',
      'address_pincode': 'Pincode',
    },
    'hi': {
      'app_title': 'क्रॉपपल्स',
      'nav_home': 'होम',
      'nav_intelligence': 'इंटेलिजेंस',
      'nav_farmer': 'किसान',
      'nav_trader': 'व्यापारी',
      'nav_customer': 'ग्राहक',
      'nav_market': 'मार्केट',
      'nav_profile': 'प्रोफ़ाइल',
      'select_role': 'भूमिका चुनें',
      'select_language': 'भाषा चुनें',
      'role_farmer': 'किसान',
      'role_trader': 'व्यापारी',
      'role_exporter': 'निर्यातक',
      'role_customer': 'ग्राहक',
      'lang_english': 'अंग्रेज़ी',
      'lang_hindi': 'हिंदी',
      'lang_telugu': 'तेलुगु',
      'daily_feed_title': 'दैनिक इंटेलिजेंस फ़ीड',
      'daily_feed_subtitle': 'रियल-टाइम मार्केट अलर्ट और एआई सिफारिशें',
      'need_recommendation': 'बेचने की सलाह चाहिए?',
      'need_recommendation_desc':
          'फेज 2 एपीआई से लाइव मार्केट गाइडेंस पाने या ऑफलाइन डेटा देखने के लिए प्राइस एडवाइज़र खोलें।',
      'open_price_advisor': 'प्राइस एडवाइज़र खोलें',
      'alert_rice_title': 'चावल की कीमतें बढ़ रहीं (8.5%)',
      'alert_rice_subtitle': 'अगले 48 घंटों में मांग चरम पर रहने की उम्मीद',
      'alert_rice_action': 'बेचने की अच्छी विंडो खुल रही है',
      'alert_peak_title': 'पीक डिमांड की स्थिति',
      'alert_peak_subtitle': 'मांग 92% पर है और खरीदारों की रुचि अधिकतम है',
      'alert_peak_action': 'बेहतर बिक्री समय',
      'alert_rain_title': 'भारी बारिश की संभावना',
      'alert_rain_subtitle': 'अगले 2 से 3 हफ्तों में सप्लाई घट सकती है',
      'alert_rain_action': 'सप्लाई पर नज़र रखें',
      'alert_sell_title': 'बेचने का सही समय: अगले 48 घंटे',
      'alert_sell_subtitle': 'कीमत पूर्वानुमान: ₹2,650/किलो पीक डिमांड पर',
      'alert_sell_action': 'अभी बेचने की सलाह',
      'farmer_hub_title': 'किसान हब',
      'farmer_operating_system': 'किसान ऑपरेटिंग सिस्टम',
      'crop_planning': 'फसल योजना',
      'crop_planning_desc': 'लाभ विश्लेषण के साथ फसल योजना बनाएं',
      'best_time_sell': 'बेचने का सही समय',
      'best_time_sell_desc': 'एआई सही कटाई समय बताता है',
      'weather_alerts': 'मौसम अलर्ट',
      'weather_alerts_desc': 'रियल-टाइम मौसम और रोग अलर्ट',
      'buyer_discovery': 'खरीदार खोज',
      'buyer_discovery_desc': 'सत्यापित खरीदारों से जुड़ें',
      'open': 'खोलें',
      'available_now': 'अभी उपलब्ध',
      'coming_soon': 'जल्द आ रहा है',
      'trader_hub_title': 'व्यापारी हब',
      'procurement_intelligence': 'प्रोक्योरमेंट इंटेलिजेंस',
      'supply_visibility': 'सप्लाई विजिबिलिटी',
      'supply_visibility_desc': 'मंडियों में रियल-टाइम इन्वेंटरी',
      'demand_forecasting': 'मांग पूर्वानुमान',
      'demand_forecasting_desc': 'क्षेत्र के अनुसार खरीदार मांग का अनुमान',
      'regional_arbitrage': 'क्षेत्रीय आर्बिट्राज',
      'regional_arbitrage_desc': 'लाभ के लिए मूल्य अंतर पहचानें',
      'inventory_tracking': 'इन्वेंटरी ट्रैकिंग',
      'inventory_tracking_desc': 'खरीदी गई इन्वेंटरी ट्रैक करें',
      'customer_hub_title': 'ग्राहक हब',
      'customer_buying_desk': 'ग्राहक खरीद डेस्क',
      'customer_buying_desc':
          'ग्राहक सब्जियां, दालें, तिलहन, मसाले और अन्य फसलें देख सकते हैं, ऑफर की तुलना कर सकते हैं और किसानों व व्यापारियों से खरीद सकते हैं।',
      'customer_marketplace_cta': 'मार्केटप्लेस फसलें देखें',
      'customer_intelligence_cta': 'मार्केट इंटेलिजेंस देखें',
      'customer_price_cta': 'प्राइस गाइडेंस देखें',
      'customer_card_market_title': 'सभी फसलें एक जगह',
      'customer_card_market_desc':
          'सब्जियां, दालें, तिलहन, मसाले और मुख्य फसलें किसान और व्यापारी ऑफर के साथ देखें।',
      'customer_card_buyers_title': 'विश्वास के साथ खरीदें',
      'customer_card_buyers_desc':
          'ऑफर भेजने से पहले लोकेशन, गुणवत्ता और कीमत देखें।',
      'customer_card_guidance_title': 'मार्केट टाइमिंग जानें',
      'customer_card_guidance_desc':
          'खरीद से पहले इंटेलिजेंस और प्राइस एडवाइज़र टूल्स का उपयोग करें।',
      'marketplace_title': 'मार्केटप्लेस',
      'buy_orders': 'खरीद ऑर्डर',
      'sell_orders': 'बिक्री ऑर्डर',
      'customer_buy_banner':
          'ग्राहक इस मार्केटप्लेस से किसानों और व्यापारियों की लाइव फसल लिस्टिंग देखकर खरीदारी के लिए ऑफर भेज सकते हैं।',
      'crop': 'फसल',
      'state': 'राज्य',
      'state_filter': 'राज्य फ़िल्टर',
      'sync_listings': 'लिस्टिंग सिंक करें',
      'no_live_sell_listings':
          'अभी कोई लाइव बिक्री लिस्टिंग नहीं है। जोड़ने वाले बटन से नई लिस्टिंग प्रकाशित करें।',
      'create_listing': 'लिस्टिंग बनाएं',
      'crop_id': 'फसल आईडी',
      'quantity_kg': 'मात्रा (किलो)',
      'quality_grade': 'गुणवत्ता ग्रेड',
      'price_per_kg': 'प्रति किलो मूल्य',
      'available_date': 'उपलब्ध तिथि (YYYY-MM-DD)',
      'description': 'विवरण',
      'enter_valid_quantity_price':
          'मात्रा और मूल्य के लिए मान्य संख्यात्मक मान दर्ज करें।',
      'publish_listing': 'लिस्टिंग प्रकाशित करें',
      'ready_to_purchase': 'जल्दी खरीदने के लिए तैयार।',
      'make_offer_for': '{crop} के लिए ऑफर दें',
      'seller': 'विक्रेता: {name}',
      'offer_price_per_kg': 'ऑफर मूल्य प्रति किलो',
      'pickup_location': 'पिकअप स्थान',
      'message': 'संदेश',
      'submit_offer': 'ऑफर भेजें',
      'enter_valid_offer_quantity':
          'ऑफर और मात्रा के लिए मान्य संख्यात्मक मान दर्ज करें।',
      'available': 'उपलब्ध: {value}',
      'make_offer': 'खरीद ऑफर भेजें',
      'available_on_views': '{date} को उपलब्ध · {views} व्यू',
      'intelligence_title': 'मार्केट इंटेलिजेंस',
      'select_commodity': 'कमोडिटी चुनें',
      'price_chart_30_days': 'मूल्य चार्ट (30 दिन)',
      'ai_price_advisor': 'एआई प्राइस एडवाइज़र',
      'ai_price_advisor_desc':
          'फेज 2 इंटेलिजेंस एपीआई से फसल-विशिष्ट सिफारिश, नजदीकी मंडी कीमतें और बेहतर बिक्री समय प्राप्त करें।',
      'supply_vs_demand': 'सप्लाई बनाम डिमांड',
      'supply_level': 'सप्लाई स्तर',
      'inventory_status': 'इन्वेंटरी स्थिति',
      'demand_level': 'मांग स्तर',
      'buyer_interest': 'खरीदार रुचि',
      'price_advisor_title': 'प्राइस एडवाइज़र',
      'live_selling_guidance': 'लाइव बिक्री मार्गदर्शन',
      'live_selling_guidance_desc':
          'अनुशंसित मूल्य, पास की मंडी तुलना और सही बिक्री समय के लिए फेज 2 एपीआई से जानकारी लें।',
      'request_inputs': 'इनपुट विवरण',
      'fetch_recommendation': 'सिफारिश लाएं',
      'enter_valid_quantity': 'कृपया किलो में सही मात्रा दर्ज करें।',
      'offline_fallback':
          'मोबाइल ऐप एपीआई तक नहीं पहुंच सका, इसलिए ऑफलाइन डेटा दिखाया जा रहा है।',
      'recommendation_suffix': '{crop} सिफारिश',
      'recommended_price': 'अनुशंसित मूल्य',
      'market_trend': 'मार्केट ट्रेंड',
      'best_selling_time': 'बेचने का सही समय: {value}',
      'nearby_markets': 'पास के बाजार',
      'profile_title': 'प्रोफ़ाइल',
      'guest_user': 'गेस्ट उपयोगकर्ता',
      'acres': 'एकड़',
      'profile': 'प्रोफ़ाइल',
      'synced_farmer_profile': 'सिंक किसान प्रोफ़ाइल',
      'soil': 'मिट्टी: {value}',
      'edit_farmer_profile': 'किसान प्रोफ़ाइल संपादित करें',
      'login': 'साइन इन',
      'logout': 'लॉग आउट',
      'transaction_history': 'लेनदेन इतिहास',
      'saved_listings': 'सेव की गई लिस्टिंग',
      'settings': 'सेटिंग्स',
      'help_support': 'सहायता और समर्थन',
      'account_sync_later': 'अकाउंट सिंक बाद में आएगा',
      'account_sync_message':
          'कोर मोबाइल अनुभव पूरा होने के बाद अकाउंट सिंक जोड़ा जाएगा।',
      'sign_in_title': 'क्रॉपपल्स में साइन इन करें',
      'sign_in_desc':
          'सुरक्षित एक बार उपयोग होने वाला सत्यापन कोड पाने के लिए अपना मोबाइल नंबर उपयोग करें।',
      'phone_number': 'फोन नंबर',
      'request_otp': 'OTP मांगें',
      'verify_otp': 'OTP सत्यापित करें',
      'resend_otp': 'OTP दोबारा भेजें',
      'otp': 'OTP',
      'farmer_profile_title': 'किसान प्रोफ़ाइल',
      'sync_profile': 'प्रोफ़ाइल सिंक करें',
      'save_profile': 'प्रोफ़ाइल सेव करें',
      'saving': 'सेव हो रहा है...',
      'fill_required_fields': 'हर आवश्यक फ़ील्ड में सही मान भरें।',
      'backend_profile_snapshot': 'बैकएंड प्रोफ़ाइल स्नैपशॉट',
      'name': 'नाम',
      'phone': 'फोन',
      'kyc': 'केवाईसी',
      'land_size': 'भूमि आकार: {value} एकड़',
      'created': 'बनाया गया: {value}',
      'farmer_profile_form': 'किसान प्रोफ़ाइल फॉर्म',
      'district': 'जिला',
      'village': 'गाँव',
      'land_size_acres': 'भूमि आकार (एकड़)',
      'soil_type': 'मिट्टी का प्रकार',
      'latitude': 'अक्षांश',
      'longitude': 'देशांतर',
      'bank_account_optional': 'बैंक खाता (वैकल्पिक)',
      'preview_local_draft':
          'प्रीव्यू मोड: इस डिवाइस पर स्थानीय किसान प्रोफ़ाइल ड्राफ्ट उपयोग हो रहा है।',
      'farmer_profile_synced_success': 'किसान प्रोफ़ाइल सफलतापूर्वक सिंक हुई।',
      'could_not_load_farmer_profile': 'किसान प्रोफ़ाइल लोड नहीं हो सकी।',
      'preview_saved_locally':
          'प्रीव्यू मोड: प्रोफ़ाइल इस डिवाइस पर स्थानीय रूप से सेव की गई।',
      'farmer_profile_saved_success': 'किसान प्रोफ़ाइल सफलतापूर्वक सेव हुई।',
      'could_not_save_farmer_profile': 'किसान प्रोफ़ाइल सेव नहीं हो सकी।',
      'signed_in_successfully': 'सफलतापूर्वक साइन इन हो गया।',
      'could_not_request_otp': 'OTP का अनुरोध नहीं किया जा सका।',
      'could_not_verify_otp': 'OTP सत्यापित नहीं हो सका।',
      'mock_code_suffix': 'अभी के लिए मॉक कोड 123456 उपयोग करें।',
      'nav_categories': 'श्रेणियाँ',
      'nav_search': 'खोजें',
      'nav_cart': 'कार्ट',
      'nav_account': 'खाता',
      'categories': 'श्रेणियाँ',
      'all': 'सभी',
      'view_all': 'सभी देखें',
      'available_products': 'उपलब्ध उत्पाद',
      'no_products': 'अभी कोई उत्पाद उपलब्ध नहीं है।',
      'search': 'खोजें',
      'search_products': 'सब्जियाँ, फल, अनाज खोजें...',
      'search_prompt': 'खोजने के लिए उत्पाद या श्रेणी लिखें।',
      'add_to_cart': 'कार्ट में जोड़ें',
      'in_cart': 'कार्ट में {quantity}',
      'not_available': 'उपलब्ध नहीं',
      'price_unavailable': 'मूल्य उपलब्ध नहीं',
      'minimum_quantity': 'न्यूनतम मात्रा',
      'grade': 'ग्रेड',
      'description_unavailable': 'उत्पाद की जानकारी उपलब्ध नहीं है।',
      'cart': 'कार्ट',
      'empty_cart': 'आपका कार्ट खाली है।',
      'browse_categories': 'श्रेणियाँ देखें',
      'subtotal': 'उप-योग',
      'delivery_fee': 'डिलीवरी शुल्क',
      'total': 'कुल',
      'cart_location_required': 'स्टॉक जाँचने के लिए डिलीवरी स्थान चुनें।',
      'resolve_cart_issues': 'कार्ट की समस्याएँ हल करें',
      'checkout_next_step': 'चेकआउट अगला कार्यान्वयन चरण है',
      'set_delivery_area': 'डिलीवरी क्षेत्र चुनें',
      'delivery_to': 'डिलीवरी',
      'pincode': 'पिनकोड',
      'check_delivery': 'डिलीवरी जाँचें',
      'check_serviceability': 'डिलीवरी उपलब्धता जाँचें',
      'invalid_pincode': 'मान्य 6 अंकों का भारतीय पिनकोड दर्ज करें।',
      'serviceable': 'डिलीवरी उपलब्ध',
      'temporarily_unavailable': 'अस्थायी रूप से अनुपलब्ध',
      'not_serviceable': 'डिलीवरी उपलब्ध नहीं',
      'commerce_offline': 'आप ऑफलाइन हैं। कनेक्शन जाँचकर फिर प्रयास करें।',
      'commerce_error': 'क्रॉपपल्स यह जानकारी लोड नहीं कर सका।',
      'retry': 'फिर प्रयास करें',
      'addresses': 'पते',
      'add_address': 'पता जोड़ें',
      'edit_address': 'पता संपादित करें',
      'manage_addresses': 'सहेजे गए डिलीवरी पते प्रबंधित करें',
      'default_address': 'डिफ़ॉल्ट',
      'make_default': 'डिफ़ॉल्ट बनाएँ',
      'edit': 'संपादित करें',
      'delete': 'हटाएँ',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'sign_in_for_addresses':
          'पते सहेजने और कार्ट बहाल करने के लिए साइन इन करें।',
      'address_label': 'लेबल',
      'address_recipient_name': 'प्राप्तकर्ता का नाम',
      'address_recipient_phone': 'प्राप्तकर्ता का फोन',
      'address_line1': 'पता पंक्ति 1',
      'address_line2': 'पता पंक्ति 2',
      'address_landmark': 'लैंडमार्क',
      'address_locality': 'इलाका',
      'address_district': 'ज़िला',
      'address_state': 'राज्य',
      'address_pincode': 'पिनकोड',
    },
    'te': {
      'app_title': 'క్రాప్‌పల్స్',
      'nav_home': 'హోమ్',
      'nav_intelligence': 'ఇంటెలిజెన్స్',
      'nav_farmer': 'రైతు',
      'nav_trader': 'వ్యాపారి',
      'nav_customer': 'కస్టమర్',
      'nav_market': 'మార్కెట్',
      'nav_profile': 'ప్రొఫైల్',
      'select_role': 'పాత్రను ఎంచుకోండి',
      'select_language': 'భాషను ఎంచుకోండి',
      'role_farmer': 'రైతు',
      'role_trader': 'వ్యాపారి',
      'role_exporter': 'ఎగుమతిదారు',
      'role_customer': 'కస్టమర్',
      'lang_english': 'ఇంగ్లీష్',
      'lang_hindi': 'హిందీ',
      'lang_telugu': 'తెలుగు',
      'daily_feed_title': 'దినసరి ఇంటెలిజెన్స్ ఫీడ్',
      'daily_feed_subtitle': 'రియల్ టైమ్ మార్కెట్ అలర్ట్స్ మరియు ఏఐ సూచనలు',
      'need_recommendation': 'అమ్మకాల సూచన కావాలా?',
      'need_recommendation_desc':
          'ఫేజ్ 2 API నుండి లైవ్ మార్కెట్ గైడెన్స్ పొందడానికి లేదా ఆఫ్లైన్ డేటాను చూడడానికి ప్రైస్ అడ్వైజర్ తెరవండి.',
      'open_price_advisor': 'ప్రైస్ అడ్వైజర్ తెరవండి',
      'alert_rice_title': 'బియ్యం ధరలు పెరుగుతున్నాయి (8.5%)',
      'alert_rice_subtitle': 'తదుపరి 48 గంటల్లో గరిష్ట డిమాండ్ వచ్చే అవకాశం',
      'alert_rice_action': 'అమ్మడానికి మంచి సమయం ప్రారంభమవుతోంది',
      'alert_peak_title': 'గరిష్ట డిమాండ్ పరిస్థితులు',
      'alert_peak_subtitle':
          'డిమాండ్ 92% వద్ద ఉంది మరియు కొనుగోలుదారుల ఆసక్తి ఎక్కువగా ఉంది',
      'alert_peak_action': 'ఉత్తమ అమ్మకాల సమయం',
      'alert_rain_title': 'భారీ వర్షాలు వచ్చే అవకాశం',
      'alert_rain_subtitle': 'తదుపరి 2 నుండి 3 వారాల్లో సరఫరా తగ్గవచ్చు',
      'alert_rain_action': 'సరఫరాను దగ్గరగా గమనించండి',
      'alert_sell_title': 'అమ్మడానికి ఉత్తమ సమయం: తదుపరి 48 గంటలు',
      'alert_sell_subtitle': 'ధర అంచనా: గరిష్ట డిమాండ్ సమయంలో ₹2,650/కిలో',
      'alert_sell_action': 'ఇప్పుడే అమ్మాలని సూచన',
      'farmer_hub_title': 'రైతు హబ్',
      'farmer_operating_system': 'రైతు ఆపరేటింగ్ సిస్టమ్',
      'crop_planning': 'పంట ప్రణాళిక',
      'crop_planning_desc': 'లాభ విశ్లేషణతో పంటలను ప్రణాళిక చేయండి',
      'best_time_sell': 'అమ్మడానికి సరైన సమయం',
      'best_time_sell_desc': 'ఏఐ సరైన కోత తేదీని సూచిస్తుంది',
      'weather_alerts': 'వాతావరణ అలర్ట్స్',
      'weather_alerts_desc': 'రియల్ టైమ్ వాతావరణ మరియు వ్యాధి అలర్ట్స్',
      'buyer_discovery': 'కొనుగోలుదారుల గుర్తింపు',
      'buyer_discovery_desc': 'ధృవీకరించిన కొనుగోలుదారులతో కలవండి',
      'open': 'తెరవండి',
      'available_now': 'ఇప్పుడు అందుబాటులో ఉంది',
      'coming_soon': 'త్వరలో వస్తుంది',
      'trader_hub_title': 'వ్యాపారి హబ్',
      'procurement_intelligence': 'ప్రోక్యూర్‌మెంట్ ఇంటెలిజెన్స్',
      'supply_visibility': 'సరఫరా విజిబిలిటీ',
      'supply_visibility_desc': 'మండీల్లో రియల్ టైమ్ ఇన్వెంటరీ',
      'demand_forecasting': 'డిమాండ్ అంచనా',
      'demand_forecasting_desc': 'ప్రాంతం వారీగా కొనుగోలుదారుల డిమాండ్ అంచనా',
      'regional_arbitrage': 'ప్రాంతీయ ఆర్భిట్రేజ్',
      'regional_arbitrage_desc': 'లాభం కోసం ధరల తేడాలను గుర్తించండి',
      'inventory_tracking': 'ఇన్వెంటరీ ట్రాకింగ్',
      'inventory_tracking_desc': 'కొనుగోలు చేసిన సరుకును ట్రాక్ చేయండి',
      'customer_hub_title': 'కస్టమర్ హబ్',
      'customer_buying_desk': 'కస్టమర్ కొనుగోలు డెస్క్',
      'customer_buying_desc':
          'కస్టమర్లు కూరగాయలు, పప్పులు, నూనెగింజలు, మసాలాలు మరియు ఇతర పంటలను ఒకే చోట చూసి రైతులు మరియు వ్యాపారుల నుండి కొనుగోలు చేయవచ్చు.',
      'customer_marketplace_cta': 'మార్కెట్‌ప్లేస్ పంటలను చూడండి',
      'customer_intelligence_cta': 'మార్కెట్ ఇంటెలిజెన్స్ చూడండి',
      'customer_price_cta': 'ధర మార్గదర్శకాన్ని చూడండి',
      'customer_card_market_title': 'అన్ని పంటలు ఒకే చోట',
      'customer_card_market_desc':
          'కూరగాయలు, పప్పులు, నూనెగింజలు, మసాలాలు మరియు ప్రధాన పంటలను రైతులు మరియు వ్యాపారుల ఆఫర్లతో చూడండి.',
      'customer_card_buyers_title': 'నమ్మకంగా కొనండి',
      'customer_card_buyers_desc':
          'ఆఫర్ ఇచ్చే ముందు స్థానం, నాణ్యత మరియు ధరను చూడండి.',
      'customer_card_guidance_title': 'మార్కెట్ టైమింగ్ తెలుసుకోండి',
      'customer_card_guidance_desc':
          'కొనుగోలు ముందు ఇంటెలిజెన్స్ మరియు ప్రైస్ అడ్వైజర్ వాడండి.',
      'marketplace_title': 'మార్కెట్‌ప్లేస్',
      'buy_orders': 'కొనుగోలు ఆర్డర్లు',
      'sell_orders': 'అమ్మకపు ఆర్డర్లు',
      'customer_buy_banner':
          'ఈ మార్కెట్‌ప్లేస్‌లో కస్టమర్లు రైతులు మరియు వ్యాపారుల లైవ్ పంట లిస్టింగ్స్ చూసి కొనుగోలు ఆఫర్లు పంపవచ్చు.',
      'crop': 'పంట',
      'state': 'రాష్ట్రం',
      'state_filter': 'రాష్ట్ర ఫిల్టర్',
      'sync_listings': 'లిస్టింగ్స్ సింక్ చేయండి',
      'no_live_sell_listings':
          'ఇప్పటికీ లైవ్ అమ్మకాల లిస్టింగ్స్ లేవు. కొత్త లిస్టింగ్ ప్రచురించడానికి యాడ్ బటన్ ఉపయోగించండి.',
      'create_listing': 'లిస్టింగ్ సృష్టించండి',
      'crop_id': 'పంట ఐడి',
      'quantity_kg': 'పరిమాణం (కిలోలు)',
      'quality_grade': 'నాణ్యత గ్రేడ్',
      'price_per_kg': 'కిలోకు ధర',
      'available_date': 'అందుబాటులో తేది (YYYY-MM-DD)',
      'description': 'వివరణ',
      'enter_valid_quantity_price':
          'పరిమాణం మరియు ధరకు సరైన సంఖ్యలను నమోదు చేయండి.',
      'publish_listing': 'లిస్టింగ్ ప్రచురించండి',
      'ready_to_purchase': 'త్వరగా కొనుగోలు చేయడానికి సిద్ధంగా ఉన్నాను.',
      'make_offer_for': '{crop} కోసం ఆఫర్ ఇవ్వండి',
      'seller': 'విక్రేత: {name}',
      'offer_price_per_kg': 'ఆఫర్ ధర కిలోకు',
      'pickup_location': 'పికప్ స్థలం',
      'message': 'సందేశం',
      'submit_offer': 'ఆఫర్ పంపండి',
      'enter_valid_offer_quantity':
          'ఆఫర్ మరియు పరిమాణానికి సరైన సంఖ్యలను నమోదు చేయండి.',
      'available': 'అందుబాటులో ఉంది: {value}',
      'make_offer': 'కొనుగోలు ఆఫర్ పంపండి',
      'available_on_views': '{date}న అందుబాటులో ఉంది · {views} వీక్షణలు',
      'intelligence_title': 'మార్కెట్ ఇంటెలిజెన్స్',
      'select_commodity': 'కమోడిటీ ఎంచుకోండి',
      'price_chart_30_days': 'ధర చార్ట్ (30 రోజులు)',
      'ai_price_advisor': 'ఏఐ ప్రైస్ అడ్వైజర్',
      'ai_price_advisor_desc':
          'ఫేజ్ 2 ఇంటెలిజెన్స్ API నుండి పంటకు సంబంధించిన సిఫార్సు, సమీప మండీ ధరలు మరియు ఉత్తమ అమ్మకాల సమయాన్ని పొందండి.',
      'supply_vs_demand': 'సరఫరా వర్సెస్ డిమాండ్',
      'supply_level': 'సరఫరా స్థాయి',
      'inventory_status': 'ఇన్వెంటరీ స్థితి',
      'demand_level': 'డిమాండ్ స్థాయి',
      'buyer_interest': 'కొనుగోలుదారుల ఆసక్తి',
      'price_advisor_title': 'ప్రైస్ అడ్వైజర్',
      'live_selling_guidance': 'లైవ్ అమ్మకాల మార్గదర్శకం',
      'live_selling_guidance_desc':
          'సిఫార్సు ధర, సమీప మండీ పోలికలు మరియు ఉత్తమ అమ్మకాల సమయం కోసం ఫేజ్ 2 API నుండి సమాచారం పొందండి.',
      'request_inputs': 'ఇన్‌పుట్ వివరాలు',
      'fetch_recommendation': 'సిఫార్సు తెమ్మండి',
      'enter_valid_quantity': 'దయచేసి కిలోలలో సరైన పరిమాణం ఇవ్వండి.',
      'offline_fallback':
          'మొబైల్ యాప్ API ని చేరుకోలేకపోయింది, అందుకే ఆఫ్లైన్ డేటా చూపిస్తున్నాం.',
      'recommendation_suffix': '{crop} సిఫార్సు',
      'recommended_price': 'సిఫార్సు ధర',
      'market_trend': 'మార్కెట్ ధోరణి',
      'best_selling_time': 'అమ్మడానికి ఉత్తమ సమయం: {value}',
      'nearby_markets': 'సమీప మార్కెట్లు',
      'profile_title': 'ప్రొఫైల్',
      'guest_user': 'గెస్ట్ యూజర్',
      'acres': 'ఎకరాలు',
      'profile': 'ప్రొఫైల్',
      'synced_farmer_profile': 'సింక్ రైతు ప్రొఫైల్',
      'soil': 'మట్టి: {value}',
      'edit_farmer_profile': 'రైతు ప్రొఫైల్ సవరించండి',
      'login': 'సైన్ ఇన్',
      'logout': 'లాగ్ అవుట్',
      'transaction_history': 'లావాదేవీ చరిత్ర',
      'saved_listings': 'సేవ్ చేసిన లిస్టింగ్స్',
      'settings': 'సెట్టింగ్స్',
      'help_support': 'సహాయం మరియు మద్దతు',
      'account_sync_later': 'అకౌంట్ సింక్ తర్వాత వస్తుంది',
      'account_sync_message':
          'కోర్ మొబైల్ అనుభవం పూర్తయ్యాక అకౌంట్ సింక్ జోడిస్తాం.',
      'sign_in_title': 'క్రాప్‌పల్స్‌లో సైన్ ఇన్ చేయండి',
      'sign_in_desc':
          'సురక్షితమైన ఒకసారి ఉపయోగించే ధృవీకరణ కోడ్ పొందడానికి మీ మొబైల్ నంబర్‌ను ఉపయోగించండి.',
      'phone_number': 'ఫోన్ నంబర్',
      'request_otp': 'OTP కోరండి',
      'verify_otp': 'OTP నిర్ధారించండి',
      'resend_otp': 'OTP మళ్లీ పంపండి',
      'otp': 'OTP',
      'farmer_profile_title': 'రైతు ప్రొఫైల్',
      'sync_profile': 'ప్రొఫైల్ సింక్ చేయండి',
      'save_profile': 'ప్రొఫైల్ సేవ్ చేయండి',
      'saving': 'సేవ్ అవుతోంది...',
      'fill_required_fields': 'ప్రతి అవసరమైన ఫీల్డ్‌లో సరైన విలువలను ఇవ్వండి.',
      'backend_profile_snapshot': 'బ్యాక్‌ఎండ్ ప్రొఫైల్ స్నాప్‌షాట్',
      'name': 'పేరు',
      'phone': 'ఫోన్',
      'kyc': 'కేవైసీ',
      'land_size': 'భూమి పరిమాణం: {value} ఎకరాలు',
      'created': 'సృష్టించబడింది: {value}',
      'farmer_profile_form': 'రైతు ప్రొఫైల్ ఫారమ్',
      'district': 'జిల్లా',
      'village': 'గ్రామం',
      'land_size_acres': 'భూమి పరిమాణం (ఎకరాలు)',
      'soil_type': 'మట్టి రకం',
      'latitude': 'అక్షాంశం',
      'longitude': 'రేఖాంశం',
      'bank_account_optional': 'బ్యాంక్ ఖాతా (ఐచ్ఛికం)',
      'preview_local_draft':
          'ప్రివ్యూ మోడ్: ఈ పరికరంలో స్థానిక రైతు ప్రొఫైల్ డ్రాఫ్ట్ ఉపయోగంలో ఉంది.',
      'farmer_profile_synced_success': 'రైతు ప్రొఫైల్ విజయవంతంగా సింక్ అయింది.',
      'could_not_load_farmer_profile': 'రైతు ప్రొఫైల్ లోడ్ కాలేదు.',
      'preview_saved_locally':
          'ప్రివ్యూ మోడ్: ప్రొఫైల్ ఈ పరికరంలో స్థానికంగా సేవ్ చేయబడింది.',
      'farmer_profile_saved_success': 'రైతు ప్రొఫైల్ విజయవంతంగా సేవ్ అయింది.',
      'could_not_save_farmer_profile': 'రైతు ప్రొఫైల్ సేవ్ కాలేదు.',
      'signed_in_successfully': 'విజయవంతంగా సైన్ ఇన్ అయ్యారు.',
      'could_not_request_otp': 'OTP కోరలేకపోయాం.',
      'could_not_verify_otp': 'OTP నిర్ధారించలేకపోయాం.',
      'mock_code_suffix': 'ప్రస్తుతం మాక్ కోడ్ 123456 ను ఉపయోగించండి.',
      'nav_categories': 'వర్గాలు',
      'nav_search': 'వెతకండి',
      'nav_cart': 'కార్ట్',
      'nav_account': 'ఖాతా',
      'categories': 'వర్గాలు',
      'all': 'అన్నీ',
      'view_all': 'అన్నీ చూడండి',
      'available_products': 'అందుబాటులోని ఉత్పత్తులు',
      'no_products': 'ప్రస్తుతం ఉత్పత్తులు అందుబాటులో లేవు.',
      'search': 'వెతకండి',
      'search_products': 'కూరగాయలు, పండ్లు, ధాన్యాలు వెతకండి...',
      'search_prompt': 'వెతకడానికి ఉత్పత్తి లేదా వర్గాన్ని నమోదు చేయండి.',
      'add_to_cart': 'కార్ట్‌కు జోడించండి',
      'in_cart': 'కార్ట్‌లో {quantity}',
      'not_available': 'అందుబాటులో లేదు',
      'price_unavailable': 'ధర అందుబాటులో లేదు',
      'minimum_quantity': 'కనీస పరిమాణం',
      'grade': 'గ్రేడ్',
      'description_unavailable': 'ఉత్పత్తి సమాచారం అందుబాటులో లేదు.',
      'cart': 'కార్ట్',
      'empty_cart': 'మీ కార్ట్ ఖాళీగా ఉంది.',
      'browse_categories': 'వర్గాలను చూడండి',
      'subtotal': 'ఉప మొత్తం',
      'delivery_fee': 'డెలివరీ రుసుము',
      'total': 'మొత్తం',
      'cart_location_required': 'స్టాక్ తనిఖీకి డెలివరీ ప్రాంతాన్ని ఎంచుకోండి.',
      'resolve_cart_issues': 'కార్ట్ సమస్యలను పరిష్కరించండి',
      'checkout_next_step': 'చెక్అవుట్ తదుపరి అమలు దశ',
      'set_delivery_area': 'డెలివరీ ప్రాంతాన్ని ఎంచుకోండి',
      'delivery_to': 'డెలివరీ',
      'pincode': 'పిన్‌కోడ్',
      'check_delivery': 'డెలివరీ తనిఖీ',
      'check_serviceability': 'డెలివరీ లభ్యతను తనిఖీ చేయండి',
      'invalid_pincode':
          'చెల్లుబాటు అయ్యే 6 అంకెల భారతీయ పిన్‌కోడ్ నమోదు చేయండి.',
      'serviceable': 'డెలివరీ అందుబాటులో ఉంది',
      'temporarily_unavailable': 'తాత్కాలికంగా అందుబాటులో లేదు',
      'not_serviceable': 'డెలివరీ అందుబాటులో లేదు',
      'commerce_offline':
          'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
      'commerce_error': 'క్రాప్‌పల్స్ ఈ సమాచారాన్ని లోడ్ చేయలేకపోయింది.',
      'retry': 'మళ్లీ ప్రయత్నించండి',
      'addresses': 'చిరునామాలు',
      'add_address': 'చిరునామా జోడించండి',
      'edit_address': 'చిరునామా సవరించండి',
      'manage_addresses': 'సేవ్ చేసిన డెలివరీ చిరునామాలను నిర్వహించండి',
      'default_address': 'డిఫాల్ట్',
      'make_default': 'డిఫాల్ట్‌గా చేయండి',
      'edit': 'సవరించండి',
      'delete': 'తొలగించండి',
      'save': 'సేవ్ చేయండి',
      'cancel': 'రద్దు చేయండి',
      'sign_in_for_addresses':
          'చిరునామాలు సేవ్ చేసి కార్ట్‌ను పునరుద్ధరించడానికి సైన్ ఇన్ చేయండి.',
      'address_label': 'లేబుల్',
      'address_recipient_name': 'స్వీకర్త పేరు',
      'address_recipient_phone': 'స్వీకర్త ఫోన్',
      'address_line1': 'చిరునామా పంక్తి 1',
      'address_line2': 'చిరునామా పంక్తి 2',
      'address_landmark': 'ల్యాండ్‌మార్క్',
      'address_locality': 'ప్రాంతం',
      'address_district': 'జిల్లా',
      'address_state': 'రాష్ట్రం',
      'address_pincode': 'పిన్‌కోడ్',
    },
  };

  String text(String key, {Map<String, String> params = const {}}) {
    final languageCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    var value =
        _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  String roleLabel(String role) {
    switch (role) {
      case 'Farmer':
        return text('role_farmer');
      case 'Trader':
        return text('role_trader');
      case 'Exporter':
        return text('role_exporter');
      case 'Customer':
        return text('role_customer');
      default:
        return role;
    }
  }

  String languageLabel(Locale locale) {
    switch (locale.languageCode) {
      case 'hi':
        return text('lang_hindi');
      case 'te':
        return text('lang_telugu');
      case 'en':
      default:
        return text('lang_english');
    }
  }
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) async => AppStrings(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppStrings> old) => false;
}
